version: '3'

services:
  bank-app:
    build: .  # Указываем текущую директорию как контекст сборки
    container_name: bank-app
    ports:
      - "8080:8080"  # Порт вашего Java-приложения
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JWT_SECRET=NUGGETS
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"


  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "80:80"  # Порт для Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Путь к вашему конфигурационному файлу Nginx
    depends_on:
      - bank-app

#  swagger-ui:
#    image: swaggerapi/swagger-ui
#    container_name: swagger-ui
#    ports:
#      - "8081:8080"  # Порт для Swagger UI
#    environment:
#      SWAGGER_JSON: /app/swagger.json
#    volumes:
#      - ./swagger.json:/app/swagger.json
#    depends_on:
#      - bank-app

volumes:
  db_data: