version: '3'

services:
  app:
    build: .  # Указываем текущую директорию как контекст сборки
    container_name: bank-app
    ports:
      - "8080:8080"  # Порт вашего Java-приложения
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JWT_SECRET=NUGGETS
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Порт для Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Путь к вашему конфигурационному файлу Nginx
    depends_on:
      - app

volumes:
  db_data: