spring:

#DB
  datasource:
    url: jdbc:postgresql://db:5432/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    hibernate: update

#Security
  jwt:
    secret: NIGGER_BIG_BLACK_COCK


#logs for terminal
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: DEBUG

#Swagger
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8080

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /swagger-ui.html