spring:
  datasource:
    url: jdbc:postgresql://db:5432/bank
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
#    hibernate.ddl-auto: none
    hibernate: update

  jwt:
    secret: NUGGETS

  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: DEBUG