spring:
  datasource:
    url: jdbc:postgresql://db:5432/bank
#    url: jdbc:postgresql://localhost:5432/soap_bank_app
    username: postgres
#    password: 1234
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
#    hibernate: update

  jwt:
    secret: NUGGETS

  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: DEBUG