spring:
  # DB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # Security
  jwt:
    secret: ${JWT_SECRET}


#logs for terminal
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: DEBUG

#Swagger
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8080

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /swagger-ui.html