name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with: 
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: 22
          script: | 
            cd /Mini-bank-web
            sudo docker-compose down
            mvn clean install
            sudo docker-compose down -d


            
