name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker-compose and deploy to server
      uses: appleboy/ssh-action@master
      with: 
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          script: |
            docker-compose down
            cd Mini-Bank-Web/
            git pull
            git fetch
            mvn clean install
            docker-compose up --build -d
