name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2

    - name: Deploy to server
      id: deploy
      uses: appleboy/ssh-action@master
      with: 
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: 22
          script: | 
            cd Mini-Bank-Web/ || { echo "Failed to change directory to /Mini-bank-web"; exit 1; }
            sudo docker-compose down || { echo "Failed to stop and remove containers"; exit 1; }
            git pull
            mvn clean install || { echo "Failed to run mvn clean install"; exit 1; }
            sudo docker-compose build || { echo "Failed to build containers"; exit 1; }
            sudo docker-compose up  || { echo "Failed to start containers"; exit 1; }
            
